In [2]:
import pandas as pd
import numpy as np

In [3]:
# Function to calculate AQI based on concentration
def calculate_aqi(cp, breakpoints):
    for (blo, bhi, ilo, ihi) in breakpoints:
        if blo <= cp <= bhi:
            return ((ihi - ilo) / (bhi - blo)) * (cp - blo) + ilo
    return np.nan  # Return NaN if the value is out of range

In [6]:
df1 = pd.read_csv("ind_day.csv")
df1.to_csv("ind_day_using.csv", index=False)
df1.head()

  City_station        Date   pm25    no    no2    nox    co    so2      o3
0        AP001  11/24/2017  71.36  1.75  20.65  12.40  0.10  10.76  109.26
1        AP001  11/25/2017  81.40  1.44  20.50  12.08  0.12  15.24  127.09
2        AP001  11/26/2017  78.32  1.26  26.00  14.85  0.14  26.96  117.44
3        AP001  11/27/2017  88.76  6.60  30.85  21.77  0.11  33.59  111.81
4        AP001  11/28/2017  64.18  2.56  28.07  17.01  0.09  19.00  138.18

In [7]:
print("Maximum values of the Parameters")
print(f" The maximum value of CO is {df1['co'].max().astype(int)}")
print(f" The maximum value of PM25 is {df1['pm25'].max().astype(int)}")
print(f" The maximum value of PM10 is {df1['nox'].max().astype(int)}")
print(f" The maximum value of PM10 is {df1['no'].max().astype(int)}")
print(f" The maximum value of NO2 is {df1['no2'].max().astype(int)}")
print(f" The maximum value of O3 is {df1['o3'].max().astype(int)}")
print(f" The maximum value of SO2 is {df1['so2'].max().astype(int)}")
print("Minimum values of the Parameters")
print(f" The minimum value of CO is {df1['co'].min().astype(int)}")
print(f" The minimum value of PM25 is {df1['pm25'].min().astype(int)}")
print(f" The minimum value of PM10 is {df1['nox'].min().astype(int)}")
print(f" The minimum value of PM10 is {df1['no'].min().astype(int)}")
print(f" The minimum value of NO2 is {df1['no2'].min().astype(int)}")
print(f" The minimum value of O3 is {df1['o3'].min().astype(int)}")
print(f" The minimum value of SO2 is {df1['so2'].min().astype(int)}")
print("Mean values of the Parameters")
print(f" The mean value of CO is {df1['co'].mean().astype(int)}")
print(f" The mean value of PM25 is {df1['pm25'].mean().astype(int)}")
print(f" The mean value of PM10 is {df1['nox'].mean().astype(int)}")
print(f" The mean value of PM10 is {df1['nox'].mean().astype(int)}")
print(f" The mean value of NO2 is {df1['no2'].mean().astype(int)}")
print(f" The mean value of O3 is {df1['o3'].mean().astype(int)}")
print(f" The mean value of SO2 is {df1['so2'].mean().astype(int)}")

Maximum values of the Parameters
 The maximum value of CO is 175
 The maximum value of PM25 is 999
 The maximum value of PM10 is 453
 The maximum value of PM10 is 437
 The maximum value of NO2 is 448
 The maximum value of O3 is 963
 The maximum value of SO2 is 186
Minimum values of the Parameters
 The minimum value of CO is 0
 The minimum value of PM25 is 0
 The minimum value of PM10 is 0
 The minimum value of PM10 is 0
 The minimum value of NO2 is 0
 The minimum value of O3 is 0
 The minimum value of SO2 is 0
Mean values of the Parameters
 The mean value of CO is 1
 The mean value of PM25 is 75
 The mean value of PM10 is 40
 The mean value of PM10 is 40
 The mean value of NO2 is 35
 The mean value of O3 is 38
 The mean value of SO2 is 13

In [8]:
pm25_breakpoints = [
    (0, 30, 0, 50),        # Good
    (31, 60, 51, 100),     # Satisfactory
    (61, 90, 101, 200),    # Moderate
    (91, 120, 201, 300),   # Poor
    (121, 250, 301, 400),  # Very Poor
    (251, float('inf'), 401, 500)  # Severe
]

co_breakpoints = [
    (0, 1, 0, 50),         # Good
    (1.1, 2, 51, 100),     # Satisfactory
    (2.1, 10, 101, 200),   # Moderate
    (10.1, 17, 201, 300),  # Poor
    (17.1, 34, 301, 400),  # Very Poor
    (34.1, float('inf'), 401, 500)  # Severe
]

nox_breakpoints = [
    (0, 40, 0, 50),        # Good
    (41, 80, 51, 100),     # Satisfactory
    (81, 180, 101, 200),   # Moderate
    (181, 280, 201, 300),  # Poor
    (281, 400, 301, 400),  # Very Poor
    (401, float('inf'), 401, 500)  # Severe
]
no_breakpoints = [
    (0, 40, 0, 50),        # Good
    (41, 80, 51, 100),     # Satisfactory
    (81, 180, 101, 200),   # Moderate
    (181, 280, 201, 300),  # Poor
    (281, 400, 301, 400),  # Very Poor
    (401, float('inf'), 401, 500)  # Severe
]

# Updated breakpoints for NO2
no2_breakpoints = [
    (0, 40, 0, 50),        # Good
    (41, 80, 51, 100),     # Satisfactory
    (81, 180, 101, 200),   # Moderate
    (181, 280, 201, 300),  # Poor
    (281, 400, 301, 400),  # Very Poor
    (401, float('inf'), 401, 500)  # Severe
]

# Updated breakpoints for O3
o3_breakpoints = [
    (0, 50, 0, 50),        # Good
    (51, 100, 51, 100),    # Satisfactory
    (101, 168, 101, 200),  # Moderate
    (169, 208, 201, 300),  # Poor
    (209, 748, 301, 400),  # Very Poor
    (749, float('inf'), 401, 500)  # Severe
]
# Updated breakpoints for SO2
so2_breakpoints = [
    (0, 40, 0, 50),        # Good
    (41, 80, 51, 100),     # Satisfactory
    (81, 380, 101, 200),   # Moderate
    (381, 800, 201, 300),  # Poor
    (801, 1600, 301, 400), # Very Poor
    (1601, float('inf'), 401, 500)  # Severe
]

In [10]:
# # Load your dataset
# df = pd.read_csv("data_using2.csv")
# print(df.head())
# # Impute missing values (scaling or filling with mean)
# imputer = SimpleImputer(strategy='mean')  # You can change strategy (mean, median, etc.)
# df['co'] = imputer.fit_transform(df[['co']])
# df['pm25'] = imputer.fit_transform(df[['pm25']])
# df['pm10'] = imputer.fit_transform(df[['pm10']])
# df['no2'] = imputer.fit_transform(df[['no2']])
# df['o3'] = imputer.fit_transform(df[['o3']])
# df['so2'] = imputer.fit_transform(df[['so2']])

In [11]:
df = pd.read_csv("ind_day_using.csv")
# Apply AQI calculations for each pollutant in the dataset
df['AQI_PM25'] = df['pm25'].apply(lambda x: calculate_aqi(x, pm25_breakpoints))
df['AQI_NOX'] = df['nox'].apply(lambda x: calculate_aqi(x, nox_breakpoints))
df['AQI_NO'] = df['no'].apply(lambda x: calculate_aqi(x, no_breakpoints))
df['AQI_CO'] = df['co'].apply(lambda x: calculate_aqi(x, co_breakpoints))
df['AQI_NO2'] = df['no2'].apply(lambda x: calculate_aqi(x, no2_breakpoints))
df['AQI_O3'] = df['o3'].apply(lambda x: calculate_aqi(x, o3_breakpoints))
df['AQI_SO2'] = df['so2'].apply(lambda x: calculate_aqi(x, so2_breakpoints))

In [13]:
# Combine the highest AQI for overall AQI per row
df['AQI'] = df[['AQI_PM25', 'AQI_NOX','AQI_NO','AQI_CO', 'AQI_NO2', 'AQI_O3', 'AQI_SO2']].max(axis=1)
df["AQI_Category"] = df["AQI"].apply(lambda x: get_AQI_bucket(x))
# Save the result to a new CSV file
df.to_csv("df_AQI.csv", index=False)

In [15]:
## AQI bucketing
def get_AQI_bucket(x):
    if x <= 50:
        return "Good"
    elif x <= 100:
        return "Satisfactory"
    elif x <= 200:
        return "Moderate"
    elif x <= 300:
        return "Poor"
    elif x <= 400:
        return "Very Poor"
    elif x > 400:
        return "Severe"
    else:
        return np.NaN

In [ ]:
df2=pd.read("ind_day.csv")
df2["AQI_Category"] = df2["AQI"].apply(lambda x: get_AQI_bucket(x))
df[~df.AQI.isna()].head(13)